services:
  shinyproxy-operator:
    image: mi-shinyproxy
    environment:
      SPO_ORCHESTRATOR: docker
      SPO_DOCKER_GID: 1234   # <-- docker group id (getent group docker ...)
    volumes:
      - ./input:/opt/shinyproxy-docker-operator/input
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/shinyproxy-docker-operator/data:/opt/shinyproxy-docker-operator/data
    group_add:
      - 998                 # <-- docker group id again
    networks:
      - sp-shared-network
    restart: always
    user: "1002"             # <-- shinyproxy user id (id -u shinyproxy)

networks:
  sp-shared-network:
    name: sp-shared-network
