services:
  shinyproxy-operator:
    image: openanalytics/shinyproxy-operator:2.3.1
    container_name: shinyproxy
    environment:
      SPO_ORCHESTRATOR: docker
      SPO_DOCKER_GID: 998
      SPO_IMAGE_PULL_POLICY: IfNotPresent
      SPO_DOCKER_DATA_DIR: /srv/MG_team/shinyproxy-docker/Operator/data
    volumes:
      - /srv/MG_team/shinyproxy-docker/Operator/input:/opt/shinyproxy-docker-operator/input
      - /srv/MG_team/shinyproxy-docker/Operator/data:/srv/MG_team/shinyproxy-docker/Operator/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    group_add:
      - 998
    networks:
      - sp-shared-network
    restart: always
    labels:
      app: shinyproxy-operator
    user: "1010"
networks:
  sp-shared-network:
    name: sp-shared-network
    external: true
